/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 island.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function IsLandModel(props) {
  const { nodes, materials } = useGLTF('/models/Island.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Island.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/models/Island.glb')
